<a href="https://colab.research.google.com/github/developeravsk/Reinforcement-Learning-Q-learning-Frozen-Lake/blob/main/Agent_learns_to_play_FrozenLake_using_Q_table(Reinforcement_learning).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
!pip install gym

In [2]:
import numpy as np
import gym
import random
import time
from IPython.display import clear_output

In [3]:
env=gym.make("FrozenLake-v0")

In [4]:
action_space_size=env.action_space.n
state_space_size=env.observation_space.n

In [5]:
print(action_space_size, state_space_size)

4 16


In [6]:
qtable=np.zeros((state_space_size, action_space_size))
print(qtable)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [7]:
total_episodes = 600000   # Total episodes
learning_rate = 0.1       # Learning rate
max_steps = 100           # Max steps per episode
gamma = 0.99              # Discounting rate

# Exploration parameters
epsilon = 1.0             # Exploration rate
max_epsilon = 1.0         # Exploration probability at start
min_epsilon = 0.01            # Minimum exploration probability 
decay_rate = 0.01            # Exponential decay rate for exploration prob

In [8]:
# List of rewards
rewards = []

# 2 For life or until learning is stopped
for episode in range(total_episodes):
    # Reset the environment
    state = env.reset()
    step = 0
    done = False
    total_rewards = 0
    
    for step in range(max_steps):
        # 3. Choose an action a in the current world state (s)
        ## First we randomize a number
        exp_exp_tradeoff = random.uniform(0, 1)
        
        ## If this number > greater than epsilon --> exploitation (taking the biggest Q value for this state)
        if exp_exp_tradeoff > epsilon:
            action = np.argmax(qtable[state,:])
            #print(exp_exp_tradeoff, "action", action)

        # Else doing a random choice --> exploration
        else:
            action = env.action_space.sample()
            #print("action random", action)
            
        
        # Take the action (a) and observe the outcome state(s') and reward (r)
        new_state, reward, done, info = env.step(action)

        # Update Q(s,a):= Q(s,a) + lr [R(s,a) + gamma * max Q(s',a') - Q(s,a)]
        # qtable[new_state,:] : all the actions we can take from new state
        qtable[state, action] = qtable[state, action] + learning_rate * (reward + gamma * np.max(qtable[new_state, :]) - qtable[state, action])
        
        total_rewards += reward
        
        # Our new state is state
        state = new_state
        
        # If done (if we're dead) : finish episode
        if done == True: 
            break
        
    # Reduce epsilon (because we need less and less exploration)
    epsilon = min_epsilon + (max_epsilon - min_epsilon)*np.exp(-decay_rate*episode) 
    rewards.append(total_rewards)


print ("Score over time: " +  str(sum(rewards)/total_episodes))
print(qtable)

Score over time: 0.680045
[[0.57526519 0.49090216 0.50562112 0.49058167]
 [0.29923148 0.3678601  0.38207531 0.49142385]
 [0.39531606 0.40783822 0.39769474 0.45566333]
 [0.24584872 0.21238753 0.39418842 0.43780364]
 [0.59094173 0.32748952 0.26544219 0.3453521 ]
 [0.         0.         0.         0.        ]
 [0.37042551 0.09936489 0.18137344 0.16042753]
 [0.         0.         0.         0.        ]
 [0.39481204 0.26489445 0.4190359  0.62532605]
 [0.46239118 0.69955965 0.3750876  0.34276345]
 [0.70737304 0.38751783 0.36905481 0.36219868]
 [0.         0.         0.         0.        ]
 [0.         0.         0.         0.        ]
 [0.48754522 0.52311551 0.76309359 0.49599872]
 [0.72410709 0.87842084 0.74793274 0.76933763]
 [0.         0.         0.         0.        ]]


In [9]:
# Play frozen lake
env.reset()

for episode in range(5):
    state = env.reset()
    step = 0
    done = False
    print("****************************************************")
    print("EPISODE ", episode)

    for step in range(max_steps):
        
        # Take the action (index) that have the maximum expected future reward given that state
        action = np.argmax(qtable[state,:])
        
        new_state, reward, done, info = env.step(action)
        
        if done:
            # Here, we decide to only print the last state (to see if our agent is on the goal or fall into an hole)
            env.render()
            if new_state == 15:
                print("We reached our Goal 🏆")
            else:
                print("We fell into a hole ☠️")
            
            # We print the number of step it took.
            print("Number of steps", step)
            
            break
        state = new_state
env.close()

****************************************************
EPISODE  0
  (Left)
SFFF
FHFH
FFFH
HFFG
We fell into a hole ☠️
Number of steps 11
****************************************************
EPISODE  1
  (Down)
SFFF
FHFH
FFFH
HFFG
We reached our Goal 🏆
Number of steps 54
****************************************************
EPISODE  2
  (Down)
SFFF
FHFH
FFFH
HFFG
We reached our Goal 🏆
Number of steps 59
****************************************************
EPISODE  3
  (Down)
SFFF
FHFH
FFFH
HFFG
We reached our Goal 🏆
Number of steps 60
****************************************************
EPISODE  4
  (Down)
SFFF
FHFH
FFFH
HFFG
We reached our Goal 🏆
Number of steps 9
